// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  id,
  author_id,
  title,
  slug,
  content,
  status,
  created_at,
  updated_at,
  archived_at
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9
) RETURNING id, author_id, title, slug, content, status, created_at, updated_at, archived_at
`

type CreatePostParams struct {
	ID         uuid.UUID
	AuthorID   uuid.UUID
	Title      string
	Slug       string
	Content    string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ArchivedAt *time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ArchivedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const findPostByID = `-- name: FindPostByID :one
SELECT
  id,
  author_id,
  title,
  slug,
  content,
  status,
  created_at,
  updated_at,
  archived_at
FROM posts
WHERE id = $1
`

func (q *Queries) FindPostByID(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, findPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET
  title = $2,
  slug = $3,
  content = $4,
  status = $5,
  updated_at = $6,
  archived_at = $7
WHERE id = $1
RETURNING id, author_id, title, slug, content, status, created_at, updated_at, archived_at
`

type UpdatePostParams struct {
	ID         uuid.UUID
	Title      string
	Slug       string
	Content    string
	Status     string
	UpdatedAt  time.Time
	ArchivedAt *time.Time
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Status,
		arg.UpdatedAt,
		arg.ArchivedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
