// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOutboxEvents = `-- name: CreateOutboxEvents :exec
INSERT INTO outbox_events (
  id,
  aggregate_type,
  aggregate_id,
  event_type,
  payload,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
`

type CreateOutboxEventsParams struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	CreatedAt     time.Time
}

func (q *Queries) CreateOutboxEvents(ctx context.Context, arg CreateOutboxEventsParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvents,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}
