// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	Email        string
	Username     string
	Name         string
	PasswordHash string
	Bio          *string
	AvatarUrl    *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
